from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add


# Schema for the agent's schema
class AgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the agent.")
    user_question : str = Field(..., description="The user's question that needs to be answered by the agent.")
    curated_prompt : str = Field(..., description="The curated user prompt.")
    prompt_query_context : str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL query.")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on curated prompt and query context.")
    is_safe : Literal["Yes","No"] = Field(..., description="A boolean indicating if the agent is safe to use.")
    comments : str = Field(..., description="Comments regarfing the safety of the generated SQL query.")
    sql_query_execution_result : str | None = Field(..., description="The result of executing the generated SQL query.")
    final_answer : str = Field(..., description="The final answer generated by the agent based on the SQL query execution result.")

# LLM as a Judge
class JudgeSchema(BaseModel):
    answer : Literal["Yes","No"] = Field(..., description="Indicates whether the sql query is safe to execute or not.")
    comment : str = Field(..., description="Additional comments or feedback regarding the SQL query.")

