from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add


# ----------------------------------------------------------- SQL Agent -----------------------------------------------------------

# Schema for the Sql Analyst Agent
class AgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the agent.")
    user_question : str = Field(..., description="The user's question that needs to be answered by the agent.")
    curated_prompt : str = Field(..., description="The curated user prompt.")
    prompt_query_context : str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL query.")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on curated prompt and query context.")
    is_safe : Literal["Yes","No"] = Field(..., description="A boolean indicating if the agent is safe to use.")
    comments : str = Field(..., description="Comments regarfing the safety of the generated SQL query.")
    sql_query_execution_result : str | None = Field(..., description="The result of executing the generated SQL query.")
    final_answer : str = Field(..., description="The final answer generated by the agent based on the SQL query execution result.")


# LLM as a Judge
# It will judge the safety of the generated SQL query and provide comments regarding its safety.
class JudgeSchema(BaseModel):
    answer : Literal["Yes","No"] = Field(..., description="Indicates whether the sql query is safe to execute or not.")
    comment : str = Field(..., description="Additional comments or feedback regarding the SQL query.")


# ----------------------------------------------------------- ETL Agent -----------------------------------------------------------

# Schema for the ETL Agent
# It will help the ETL Agent to perform the right ETL operations on the data stored in the file as per the user's question.
class ETLAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the ETL agent from API endpoints.")


# ----------------------------------------------------------- DATA AGENT -----------------------------------------------------------

# class for routing decision regarding the choice of agent
# Schema for DATA AGENT
class RouterSchema(BaseModel):
    answer : Literal["SQL_Analyst","ETL_Analyst"] = Field(..., description="Indicates which agent should be used for the given task.")
    comments : str = Field(..., description="Additional comments or feedback regarding the routing decision.")


# Schema for messages for Router Schema
# It will help the Data Agent to make routing decisions regarding the choice of agent based on the user's question 
# and the context provided by the LLM.
class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the Data Agent for routing decisions.")
    router_response : Literal["SQL_Analyst", "ETL_Analyst", ""] = Field(..., description="The response from the router indicating which agent to use for the given task.")